const ROUTES="../data/bus-routes.json";const NETWORK="https://raw.githubusercontent.com/kenzuko/transit-jotrip/main/data/network.json";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={routes:null,network:null,current:"17",vehicles:[]};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function route(){return state.routes?.routes?.find(r=>r.id===state.current)}
function renderTabs(){const host=$("#routeTabs");host.innerHTML=(state.routes.routes||[]).map(r=>'<button data-route="'+r.id+'" class="'+(r.id===state.current?"active":"")+'">🚌 Tuyến '+r.id+'</button>').join("");host.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.current=b.dataset.route;renderTabs();renderRoute()})}
function renderRoute(){const r=route();if(!r)return;$("#routeTitle").textContent="🚌 Tuyến "+r.id+" · "+r.name;$("#routeMeta").textContent=r.window+" · "+r.frequency;$("#routeSource").textContent=r.source_kind==="schedule_frequency"?"Lịch + tần suất công bố":"Nguồn live";$("#stopSelect").innerHTML=r.stops.map((s,i)=>'<option value="'+i+'">'+esc(s)+'</option>').join("");$("#stopList").innerHTML=r.stops.map((s,i)=>'<div class="stop-row"><i class="stop-dot"></i><div><strong>'+esc(s)+'</strong><small>Điểm '+(i+1)+' / '+r.stops.length+'</small></div><span class="pill info">Theo tuyến</span></div>').join("");renderVehicles()}
function renderVehicles(){const live=state.vehicles.filter(v=>String(v.route_id)===state.current);$("#vehicleCount").textContent=state.vehicles.length;if(!live.length){$("#vehicleBoard").innerHTML='<div class="empty">Chưa nhận được vị trí trực tiếp đã xác minh cho tuyến '+state.current+'.</div>';$("#nearStop").textContent="Hiện trang chỉ có lịch chạy công bố. Vị trí xe sẽ xuất hiện khi có dữ liệu chính thức.";return}$("#vehicleBoard").innerHTML=live.map(v=>'<div class="vehicle-card"><div class="vehicle-icon">🚌</div><div><strong>Xe '+esc(v.vehicle_id||"")+'</strong><small>'+esc(v.current_stop||v.position_label||"Đang chạy")+'</small></div><span class="pill good">TRỰC TIẾP</span></div>').join("")}
function renderShuttles(){$("#shuttleCount").textContent=state.routes.shuttles?.length||0;$("#shuttleGrid").innerHTML=(state.routes.shuttles||[]).map(x=>'<article class="mini-card"><span>🚌 '+esc(x.id)+'</span><strong>'+esc(x.name)+'</strong><p>'+esc(x.window)+' · '+esc(x.frequency)+'</p></article>').join("")}
async function load(){try{$("#refreshBtn").textContent="…";const [a,b]=await Promise.all([fetch(ROUTES+"?t="+Date.now(),{cache:"no-store"}),fetch(NETWORK+"?t="+Date.now(),{cache:"no-store"})]);state.routes=await a.json();state.network=await b.json();state.vehicles=Array.isArray(state.network.vehicles)?state.network.vehicles:[];$("#feedState").textContent=state.vehicles.length?"Vị trí trực tiếp":"Lịch công bố";$("#liveNote").textContent=state.vehicles.length?"Đã kết nối vị trí xe trực tiếp.":"Hiện hệ thống chưa nhận được vị trí xe trực tiếp. Lịch tuyến vẫn được hiển thị theo nguồn công bố và không tự tạo vị trí xe.";$("#updatedAt").textContent="Lịch xác minh "+state.routes.verified_at+" · dữ liệu tuyến lúc "+new Date(state.network.generated_at).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Ho_Chi_Minh"});$("#routeCount").textContent=state.routes.routes.length;renderTabs();renderRoute();renderShuttles()}catch(e){$("#feedState").textContent="Chưa tải được";$("#liveNote").textContent="Dữ liệu xe buýt đang tạm thời chưa tải được. Vui lòng thử lại sau."}finally{$("#refreshBtn").textContent="↻"}}
$("#stopSelect").onchange=()=>renderVehicles();$("#refreshBtn").onclick=load;load();
