const LIVE="https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-marine-ops/data/marine_ops/latest.json";
const HISTORY="../data/cano-history.json";const STATIC="../data/cano.json";
const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function pill(state){if(state==="RUNNING"||state==="DIRECT_CONFIRMED")return"good";if(state==="SUSPENDED")return"bad";return"watch"}
function label(state){return({RUNNING:"Đang hoạt động",SUSPENDED:"Tạm dừng",DIRECT_CONFIRMED:"Đã xác nhận",FIELD_REQUIRED:"Cần xác nhận",UNKNOWN:"Chưa rõ"})[state]||"Chưa rõ"}
function fmt(iso){if(!iso)return"-";return new Date(iso).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh",hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit",year:"numeric"})}
function renderLive(d){const c=d?.categories?.cano||{};$("#liveState").textContent=label(c.state);$("#liveState").className="pill "+pill(c.state);$("#updatedAt").textContent="Cập nhật "+fmt(d.collected_at_vn)+" · JoTrip Marine Ops";$("#todayMeta").textContent=d.source_date||"";$("#currentLabel").textContent=label(c.state);$("#evidenceCount").textContent=c.evidence_count??0;$("#confidence").textContent=(c.confidence_cap??0)+"/100";if(c.state==="FIELD_REQUIRED"){$("#heroTitle").textContent="Chưa đủ bằng chứng để kết luận cano chạy hay dừng.";$("#heroLead").textContent="Hệ thống đang chờ xác nhận trực tiếp từ thực địa/đơn vị vận hành. Tàu cao tốc và phà không được dùng để suy trạng thái cano."}else{$("#heroTitle").textContent=label(c.state)+".";$("#heroLead").textContent="Trạng thái được dựng từ bằng chứng riêng của nhóm cano."}
const ev=c.evidence||[];$("#todayRows").innerHTML=ev.length?ev.map(x=>'<tr><td>'+esc(x.issued_at_text||fmt(d.collected_at_vn))+'</td><td><strong>Cano</strong></td><td><span class="pill '+pill(c.state)+'">'+esc(label(c.state))+'</span></td><td>'+esc(x.evidence_class||"-")+'</td><td>'+esc(x.source||"-")+'<small>'+esc(x.source_tier||"")+'</small></td><td>'+esc(x.status||x.note||"-")+'</td></tr>').join(""):'<tr><td>'+esc(fmt(d.collected_at_vn))+'</td><td><strong>Cano</strong></td><td><span class="pill watch">'+esc(label(c.state))+'</span></td><td>0 bằng chứng trực tiếp</td><td>Marine Ops</td><td>Không suy từ tàu/phà. Cần xác nhận thực địa.</td></tr>'}
function renderHistory(d){$("#historyRows").innerHTML=(d.events||[]).slice().reverse().map(x=>'<tr><td><strong>'+esc(x.date)+(x.time?'<small>'+esc(x.time)+'</small>':'')+'</strong></td><td><span class="pill '+pill(x.state)+'">'+esc(x.label||label(x.state))+'</span></td><td>'+esc(x.scope||"Cano")+'</td><td>'+esc(x.note||"-")+'</td><td>'+esc(x.source?.label||"-")+'<small>'+esc(x.source?.tier||"")+'</small></td></tr>').join("")}
function renderTour(d){const t=d.tour_intro||{};$("#tourTitle").textContent=t.title||"Tour 3 đảo An Thới";$("#tourSummary").textContent=t.summary||"";$("#tourChecklist").innerHTML=(t.checklist||[]).map(x=>'<li>'+esc(x)+'</li>').join("");$("#tourTags").innerHTML=(t.hashtags||[]).map(x=>'<span>'+esc(x)+'</span>').join("")}
async function load(){try{$("#refreshBtn").textContent="…";const [a,b,c]=await Promise.all([fetch(LIVE+"?t="+Date.now(),{cache:"no-store"}),fetch(HISTORY+"?t="+Date.now(),{cache:"no-store"}),fetch(STATIC+"?t="+Date.now(),{cache:"no-store"})]);renderLive(await a.json());renderHistory(await b.json());renderTour(await c.json())}catch(e){$("#liveState").textContent="Không tải được dữ liệu";$("#todayRows").innerHTML='<tr><td colspan="6" class="empty">Không tải được lớp vận hành cano.</td></tr>'}finally{$("#refreshBtn").textContent="↻"}}$("#refreshBtn").onclick=load;load();
