const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const resultStyle=document.createElement("style");resultStyle.textContent='.handbook-result{position:relative;display:grid;gap:4px;padding:13px 34px 13px 2px;border-top:1px solid var(--line)}.handbook-result>span{color:var(--ink2);font-size:9px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.handbook-result>strong{color:var(--ink);font-size:14px}.handbook-result>small{color:#526a65;font-size:12px;line-height:1.45}.handbook-result:after{content:"→";position:absolute;right:5px;top:50%;transform:translateY(-50%);color:var(--coral);font-weight:900}';document.head.appendChild(resultStyle);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").replace(/Đ/g,"D").toLowerCase();
const initialGuideQuery=new URLSearchParams(location.search).get("q")||"";const state={search:null,stay:null,itineraries:null,practical:null,guide:null};

function searchDocuments(documents,query){const q=norm(query).trim();if(!q)return[];const terms=q.split(/\s+/).filter(Boolean);return(documents||[]).map(doc=>{const title=norm(doc.title),aliases=norm((doc.aliases||[]).join(" ")),body=norm(doc.search_text);let score=0;if(doc.type==="knowledge")score+=8;if(title===q)score+=40;if(title.includes(q))score+=24;if(aliases.includes(q))score+=18;if(body.includes(q))score+=10;terms.forEach(t=>{if(title.includes(t))score+=5;if(aliases.includes(t))score+=3;if(body.includes(t))score+=1});return{doc,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.doc.title.localeCompare(b.doc.title,"vi")).slice(0,10)}
const TYPE_LABEL={place:"Điểm đến",activity:"Trải nghiệm",hotel:"Khách sạn",hotel_tier:"Hạng khách sạn",practical:"Thông tin cần biết",price:"Giá tham khảo",access:"Di chuyển",itinerary:"Lịch trình",food:"Ẩm thực",history:"Lịch sử",culture:"Văn hóa",utility:"Tiện ích",knowledge:"Bài cẩm nang"};
function renderSearch(query){const box=$("#guideSearchResults"),results=searchDocuments(state.search?.documents,query);box.hidden=false;box.innerHTML='<div class="search-results-head"><div><span>KẾT QUẢ PHÙ HỢP</span><strong>'+esc(query)+'</strong></div><b>'+results.length+' mục</b></div>'+(results.length?results.map(({doc})=>'<a class="handbook-result" href="'+esc(doc.route||"#")+'"><span>'+esc(TYPE_LABEL[doc.type]||"Cẩm nang")+'</span><strong>'+esc(doc.title)+'</strong><small>'+esc(doc.type==="knowledge"?(doc.summary||"Mở bài cẩm nang"):((doc.aliases||[]).slice(0,3).join(" · ")||"Mở nội dung chi tiết"))+'</small></a>').join(""):'<div class="search-empty">Chưa thấy mục phù hợp. Hãy thử một từ ngắn hơn.</div>');box.scrollIntoView({behavior:"smooth",block:"nearest"})}

const INTENTS={
 first:{title:"Lần đầu đặt chân tới Phú Quốc? Ưu tiên ngay 3 nguyên tắc sống còn này.",steps:["Chia để trị: Mỗi ngày chỉ lấy một vùng làm trục chính, tuyệt đối đừng chạy bạt mạng từ Bắc chí Nam.","Đặt phòng thông minh: Lịch trình bạn định quẩy ở khu nào nhiều nhất thì hãy book khách sạn gần đó.","Linh hoạt lịch biển: Đừng chốt cứng ngày đi đảo từ nhà; cứ xem dự báo thời tiết, ngày nào trời đẹp nắng trong thì ưu tiên đẩy lịch đi biển lên."],links:[["Nhìn ba vùng","#zones"],["Chọn khu ở","#stay"],["Xem thời tiết & biển","../weather/"]]},
 family:{title:"Kinh nghiệm đưa con mọn đi chơi là: Càng ít điểm càng vui, đừng làm bọn trẻ kiệt sức.",steps:["Nếu đi Bắc đảo, hãy cho các bé chọn: Đi xem thú ở Safari HOẶC chơi trò chơi ở VinWonders. Cố nhét cả hai vào một ngày là một cơn ác mộng.","Trẻ em rất ghét ngồi xe lâu, nên nếu định chơi quanh Bắc đảo nhiều thì book luôn phòng trên đó cho nhàn.","Ưu tiên bao xe riêng hoặc gọi taxi, vừa mát mẻ vừa chủ động, đỡ lích kích cảnh ôm đồ đạc và con cái đợi xe chặng này chặng kia."],links:[["Xem điểm tham quan","../places/"],["Chọn nhịp theo số ngày","#days"],["Xe buýt & trung chuyển","../bus/"]]},
 beach:{title:"Đi biển Phú Quốc đẹp hay không là do bạn chọn đúng bãi vào đúng ngày, chứ đừng mù quáng tin vào hai chữ \"mùa khô\" hay \"mùa mưa\".",steps:["Bắt buộc phải check hướng gió, khả năng mưa và độ lớn của sóng tại đúng cái bãi mà bạn chuẩn bị đi.","Nếu bao cano ra đảo nhỏ An Thới, sáng sớm hôm đó phải gọi hỏi lại xem cano có được phép chạy không và biển ngoài đó có êm không.","Thời tiết biển đảo lật như bánh tráng, luôn phải thủ sẵn một phương án đi chơi trên bờ để \"quay xe\" kịp thời."],links:[["Thời tiết & biển","../weather/"],["Cano & tour đảo","../cano/"],["Các điểm biển","../places/"]]},
 rain:{title:"Trời mưa không có nghĩa là chuyến đi bỏ đi đâu, linh hoạt chút là vẫn vui. Riêng khi có cảnh báo thời tiết nguy hiểm, an toàn vẫn phải được ưu tiên.",steps:["Biển động, sóng lớn thì mạnh dạn hủy tour đảo đi, đừng tiếc rẻ cố đi rồi say sóng mật xanh mật vàng.","Lập tức chuyển hướng sang những hoạt động phù hợp với điều kiện thời tiết: Thăm nhà thùng nước mắm nếu đang đón khách, kiếm quán hải sản ngon nhâm nhi hoặc đi cafe, spa.","Đừng nhìn cái icon mưa to tướng trên app mà nản. Hãy xem dự báo chi tiết theo giờ, biết đâu vẫn có những khoảng tạnh ráo để tranh thủ đi chơi."],links:[["Thời tiết & biển","../weather/"],["Ăn Phú Quốc","../food/"],["Tìm phương án khác","#search"]]},
 stay:{title:"Bài toán muôn thuở: Phải khoanh vùng được khu mình thích trước, rồi mới bới tìm khách sạn.",steps:["Khu trung tâm Dương Đông là lựa chọn \"an toàn\" cho người mới: Cái gì cũng có, ăn uống nhòe mỏ, đi nhiều hướng cũng tiện.","Khu Bãi Trường thì có nhiều lựa chọn lưu trú thuận tiện ra sân bay, vừa là tọa độ ngắm hoàng hôn đỉnh chóp.","Lên Bắc đảo ở nếu bạn chỉ muốn cắm trại ở Safari và VinWonders; xuống Nam đảo ở nếu mục đích chính là đi cáp treo Hòn Thơm và quẩy Sunset Town."],links:[["So các khu","#stay"],["Xem điểm tham quan","../places/"]]},
 transport:{title:"Ở Phú Quốc, khoảng cách tính bằng kilomet không quan trọng bằng việc bạn tốn bao nhiêu thời gian ngồi trên xe.",steps:["Đường từ sân bay về trung tâm Dương Đông khá gần và đi rẹt cái là tới.","Nhắc lại lần thứ N: Bắc đảo và Nam đảo nằm ở hai thái cực, đừng hứng lên sáng chơi Bắc chiều chạy Nam, cực kỳ rã rời.","Cần tra cứu lịch chuyến bay, tàu/phà cao tốc hay lộ trình xe buýt thì mở ngay trang thông tin di chuyển ra xem cho chuẩn nhé."],links:[["Sân bay","../airport/"],["Tàu & phà","../ferry/"],["Xe buýt & trung chuyển","../bus/"]]},
 culture:{title:"Đừng chỉ tắm biển, hãy thử chạm vào cái hồn của đảo qua nghề truyền thống, nếp làng và ký ức lịch sử.",steps:["Đã cất công đi thì hãy tìm đến những nhà thùng vẫn còn đang ủ chượp nước mắm thật sự, sẽ thú vị hơn nhiều việc chui vào mấy trạm dừng chân chỉ rặt bày hàng để bán.","Vườn tiêu là một phần lịch sử kinh tế rất hay của đảo mà nhiều người vô tình bỏ lỡ khi mải miết đi tìm các khu check-in sang chảnh.","Khi đến Dinh Cậu hay Nhà tù Phú Quốc, hãy chậm lại để hiểu bối cảnh lịch sử của nó, đừng biến nơi đây thành phông nền chỉ để chụp ảnh sống ảo."],links:[["Tìm nước mắm","#search"],["Tìm hồ tiêu","#search"],["Xem điểm tham quan","../places/"]]},
 international:{title:"Lưu ý cực quan trọng cho bạn bè quốc tế: Check kỹ thủ tục giấy tờ trước khi \"xuống tiền\" mua vé máy bay hay vé tour khó hoàn hủy.",steps:["Chính sách miễn visa Phú Quốc có những điều kiện cụ thể đi kèm. Nếu định bay tiếp vào đất liền Việt Nam, bạn cần kiểm tra xem quốc tịch và giấy tờ của mình có đáp ứng điều kiện nhập cảnh hay không.","Cà thẻ thì tiện thật, nhưng tốt nhất vẫn nên dắt túi một ít tiền mặt VNĐ để lỡ có ăn vặt hay mua đồ lặt vặt. Một số cửa hàng nhỏ ở đảo không chấp nhận cà thẻ.","\"Nhập gia tùy tục\": Khi bước vào những nơi tôn nghiêm hay khu di tích, hãy ăn mặc kín đáo và giữ ý tứ khi chụp ảnh, điều đó thể hiện sự tôn trọng với văn hóa sở tại."],links:[["Tìm visa","#search"],["Khẩn cấp & tiện ích","../utilities/"]]}
}
function renderIntent(id){const x=INTENTS[id];if(!x)return;$$("[data-intent]").forEach(b=>b.classList.toggle("active",b.dataset.intent===id));$("#smartAnswer").innerHTML='<div><span>GỢI Ý CHO BẠN</span><h3>'+esc(x.title)+'</h3><ol>'+x.steps.map(s=>'<li>'+esc(s)+'</li>').join("")+'</ol><div class="answer-links">'+x.links.map(([label,url])=>'<a href="'+esc(url)+'">'+esc(label)+' →</a>').join("")+'</div></div>'}
function renderStatic(){
 $("#zoneRail").innerHTML=state.guide.zones.map(z=>'<article class="zone-card" data-zone-id="'+esc(z.id)+'"><img src="'+esc(z.image)+'" alt="'+esc(z.name)+'"><div><span>'+esc(z.tag)+'</span><h3>'+esc(z.name)+'</h3><p>'+esc(z.summary)+'</p><small>'+esc(z.best_for)+'</small></div></article>').join("");
 $("#stayGrid").innerHTML=state.stay.areas.map(a=>'<article class="stay-card"><span>'+esc(a.vibe)+'</span><h3>'+esc(a.name)+'</h3><p><b>Hợp:</b> '+esc(a.best_for.join(" · "))+'</p><p><b>Điểm mạnh:</b> '+esc(a.pros.join(" · "))+'</p><small>'+esc(a.watch.join(" · "))+'</small></article>').join("");
 const hotelAreas=state.guide?.hotels?.areas||[];
 const hotelHost=$("#guideHotelGroups");
 if(hotelHost)hotelHost.innerHTML=hotelAreas.length?'<div class="guide-hotel-head"><span>KHÁCH SẠN THEO KHU</span><strong>Một vài cái tên để bạn hình dung khu này có gì.</strong><small>Không phải bảng xếp hạng. Danh sách đầy đủ nằm ở mục Khách sạn.</small></div>'+hotelAreas.map(a=>'<article class="guide-hotel-group"><span>'+esc(a.name)+'</span><strong>'+esc(a.hotels)+'</strong><p>'+esc(a.note||"")+'</p></article>').join(""):'';
 $("#mealPlans").innerHTML=state.stay.meal_plans.map(x=>'<div><strong>'+esc(x.code)+'</strong><span>'+esc(x.meaning)+'</span></div>').join("");
 $("#dayGrid").innerHTML=state.itineraries.duration_guides.map(x=>'<button type="button" data-days="'+x.days+'"><span>'+esc(x.label)+'</span><strong>'+esc(x.principle)+'</strong><small>'+esc(x.weather_rule||x.avoid||"")+'</small></button>').join("");
 $("#routeIdeas").innerHTML='<div class="route-answer"><span>CHỌN SỐ NGÀY Ở TRÊN</span><strong>Chọn số ngày để xem nhịp đi vừa sức hơn.</strong></div>';
 $$("[data-days]").forEach(b=>b.onclick=()=>{const days=Number(b.dataset.days),d=state.itineraries.duration_guides.find(x=>x.days===days),templates=state.itineraries.templates.filter(x=>x.title.startsWith(String(days)));$$("[data-days]").forEach(x=>x.classList.toggle("active",x===b));$("#routeIdeas").innerHTML='<div class="route-answer"><span>'+esc(d.label)+'</span><strong>'+esc(d.principle)+'</strong><p>'+esc(d.weather_rule||d.avoid||"")+'</p>'+(templates.length?'<div class="route-template">'+templates.map(t=>'<b>'+esc(t.title)+'</b><ol>'+t.days.map(day=>'<li>'+esc(Array.isArray(day)?day.join(" · "):day)+'</li>').join("")+'</ol>').join("")+'</div>':'')+'</div>'});
}
Promise.all([
 fetch("data.json",{cache:"default"}).then(r=>r.json()),
 fetch("../data/views/search-index.json",{cache:"default"}).then(r=>r.json()),
 fetch("../data/stay.json",{cache:"default"}).then(r=>r.json()),
 fetch("../data/itineraries.json",{cache:"default"}).then(r=>r.json()),
 fetch("../data/practical-guide.json",{cache:"default"}).then(r=>r.json())
]).then(([guide,search,stay,itineraries,practical])=>{Object.assign(state,{guide,search,stay,itineraries,practical});$("#sourceMeta").textContent="Điểm đến, lịch trình và những điều cần biết - chọn đúng thứ bạn đang cần là đủ.";$("#handbookCoverage").textContent=(search.documents||[]).length+" mục có thể tìm";const featured=["visa","tàu cao tốc","khách sạn","Hòn Thơm","ẩm thực","APEC","Bãi Sao","gói bữa ăn"];$("#knowledgeGrid").innerHTML=featured.map((q,i)=>'<button type="button" data-guide-query="'+esc(q)+'"><span>GỢI Ý '+String(i+1).padStart(2,"0")+'</span><strong>'+esc(q)+'</strong><small>Xem nội dung liên quan</small></button>').join("");$$("[data-guide-query]").forEach(b=>b.onclick=()=>{$("#guideQ").value=b.dataset.guideQuery;renderSearch(b.dataset.guideQuery)});renderStatic();renderIntent("first");if(initialGuideQuery){$("#guideQ").value=initialGuideQuery;renderSearch(initialGuideQuery)}}).catch(e=>{$("#sourceMeta").textContent="Cẩm nang chưa mở được lúc này. Thử lại sau một chút nhé.";console.warn(e)});
$$("[data-intent]").forEach(b=>b.onclick=()=>renderIntent(b.dataset.intent));$("#guideSearch").onsubmit=e=>{e.preventDefault();const q=$("#guideQ").value.trim();if(q)renderSearch(q)};$("#guideQ").oninput=()=>{if(!$("#guideQ").value.trim())$("#guideSearchResults").hidden=true};
