const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const resultStyle=document.createElement("style");resultStyle.textContent='.handbook-result{position:relative;display:grid;gap:4px;padding:13px 34px 13px 2px;border-top:1px solid var(--line)}.handbook-result>span{color:var(--ink2);font-size:9px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.handbook-result>strong{color:var(--ink);font-size:14px}.handbook-result>small{color:#526a65;font-size:12px;line-height:1.45}.handbook-result:after{content:"→";position:absolute;right:5px;top:50%;transform:translateY(-50%);color:var(--coral);font-weight:900}';document.head.appendChild(resultStyle);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").replace(/Đ/g,"D").toLowerCase();
const initialGuideQuery=new URLSearchParams(location.search).get("q")||"";const state={search:null,stay:null,itineraries:null,practical:null,guide:null};

function searchDocuments(documents,query){const q=norm(query).trim();if(!q)return[];const terms=q.split(/\s+/).filter(Boolean);return(documents||[]).map(doc=>{const title=norm(doc.title),aliases=norm((doc.aliases||[]).join(" ")),body=norm(doc.search_text);let score=0;if(title===q)score+=40;if(title.includes(q))score+=24;if(aliases.includes(q))score+=18;if(body.includes(q))score+=10;terms.forEach(t=>{if(title.includes(t))score+=5;if(aliases.includes(t))score+=3;if(body.includes(t))score+=1});return{doc,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.doc.title.localeCompare(b.doc.title,"vi")).slice(0,10)}
const TYPE_LABEL={place:"Điểm đến",activity:"Trải nghiệm",hotel:"Khách sạn",hotel_tier:"Hạng khách sạn",practical:"Thông tin cần biết",price:"Giá tham khảo",access:"Di chuyển",itinerary:"Lịch trình",food:"Ẩm thực",history:"Lịch sử",culture:"Văn hóa",utility:"Tiện ích"};
function renderSearch(query){const box=$("#guideSearchResults"),results=searchDocuments(state.search?.documents,query);box.hidden=false;box.innerHTML='<div class="search-results-head"><div><span>KẾT QUẢ PHÙ HỢP</span><strong>'+esc(query)+'</strong></div><b>'+results.length+' mục</b></div>'+(results.length?results.map(({doc})=>'<a class="handbook-result" href="'+esc(doc.route||"#")+'"><span>'+esc(TYPE_LABEL[doc.type]||"Cẩm nang")+'</span><strong>'+esc(doc.title)+'</strong><small>'+esc((doc.aliases||[]).slice(0,3).join(" · ")||"Mở nội dung chi tiết")+'</small></a>').join(""):'<div class="search-empty">Chưa thấy mục phù hợp. Hãy thử một từ ngắn hơn.</div>');box.scrollIntoView({behavior:"smooth",block:"nearest"})}

const INTENTS={
 first:{title:"Lần đầu tới đảo: làm 3 việc trước.",steps:["Chọn một vùng làm trục cho mỗi ngày","Chọn khu ở theo nhịp chuyến đi, không theo tên resort trước","Để ngày biển vào ngày dự báo đẹp nhất"],links:[["Ba vùng","#zones"],["Chọn nơi ở","#stay"],["Xem thời tiết live","../weather/"]]},
 family:{title:"Gia đình: đừng biến chuyến đi thành cuộc chạy điểm.",steps:["Nếu đi Bắc đảo, chọn Safari hoặc VinWonders làm trục chính","Ở gần Bắc đảo nếu phần lớn ngày dành cho Safari/VinWonders","Xe riêng hoặc taxi thường nhẹ hơn gọi từng chặng"],links:[["Điểm tham quan","../places/"],["Có mấy ngày?","#days"],["Xe buýt & shuttle","../bus/"]]},
 beach:{title:"Đi biển: tình trạng trong ngày quan trọng hơn tên mùa.",steps:["Xem đúng bờ biển, gió và sóng","Tour An Thới cần xác nhận cano/đơn vị vận hành sáng hôm đi","Luôn giữ phương án B trong đảo nếu biển đổi nhanh"],links:[["Thời tiết & biển","../weather/"],["Cano & tour đảo","../cano/"],["Điểm biển","../places/"]]},
 rain:{title:"Trời xấu không có nghĩa là mất ngày.",steps:["Đừng cố giữ tour biển chỉ vì đã lên lịch","Có thể chuyển sang nhà thùng, vườn tiêu, chợ, spa hoặc ăn uống","Dùng thời tiết trực tiếp để tìm khoảng thời gian thuận lợi hơn trong ngày"],links:[["Thời tiết & biển","../weather/"],["Ăn Phú Quốc","../food/"],["Tìm phương án khác","#search"]]},
 stay:{title:"Chọn khu trước, rồi mới chọn khách sạn.",steps:["Dương Đông cân bằng cho khách lần đầu","Bãi Trường thuận sân bay, resort và hoàng hôn","Bắc đảo hợp gia đình dành nhiều thời gian cho cụm vui chơi; Nam đảo hợp Hòn Thơm/Sunset Town"],links:[["Xem các khu","#stay"],["Điểm tham quan","../places/"]]},
 transport:{title:"Di chuyển: đọc bằng thời gian, không chỉ kilomet.",steps:["Sân bay → Dương Đông thường 15-25 phút","Bắc ↔ Nam có thể 70-100 phút","Chuyến bay, tàu/phà, bus là lớp live riêng"],links:[["Sân bay","../airport/"],["Tàu & phà","../ferry/"],["Bus & shuttle","../bus/"]]},
 culture:{title:"Muốn hiểu đảo: đi qua nghề, làng và ký ức.",steps:["Nhà thùng còn vận hành thật đáng hơn điểm chỉ bán hàng","Vườn tiêu cho thấy phần đất và nông nghiệp của đảo","Dinh Cậu và Nhà tù cần được đọc bằng bối cảnh, không chỉ check-in"],links:[["Tìm nước mắm","#search"],["Tìm hồ tiêu","#search"],["Điểm tham quan","../places/"]]},
 international:{title:"Khách quốc tế: kiểm tra giấy tờ trước khi mua vé khó hoàn.",steps:["Cơ chế miễn thị thực Phú Quốc có điều kiện riêng, không tự động áp dụng cho đi tiếp đất liền","Mang cả thẻ và một ít VND","Ở nơi tín ngưỡng/di tích nên ăn mặc và ứng xử phù hợp"],links:[["Tìm visa","#search"],["Khẩn cấp & tiện ích","../utilities/"]]}
};
function renderIntent(id){const x=INTENTS[id];if(!x)return;$$("[data-intent]").forEach(b=>b.classList.toggle("active",b.dataset.intent===id));$("#smartAnswer").innerHTML='<div><span>CÂU TRẢ LỜI NHANH</span><h3>'+esc(x.title)+'</h3><ol>'+x.steps.map(s=>'<li>'+esc(s)+'</li>').join("")+'</ol><div class="answer-links">'+x.links.map(([label,url])=>'<a href="'+esc(url)+'">'+esc(label)+' →</a>').join("")+'</div></div>'}
function renderStatic(){
 $("#zoneRail").innerHTML=state.guide.zones.map(z=>'<article class="zone-card"><img src="'+esc(z.image)+'" alt="'+esc(z.name)+'"><div><span>'+esc(z.tag)+'</span><h3>'+esc(z.name)+'</h3><p>'+esc(z.summary)+'</p><small>'+esc(z.best_for)+'</small></div></article>').join("");
 $("#stayGrid").innerHTML=state.stay.areas.map(a=>'<article class="stay-card"><span>'+esc(a.vibe)+'</span><h3>'+esc(a.name)+'</h3><p><b>Hợp:</b> '+esc(a.best_for.join(" · "))+'</p><p><b>Điểm mạnh:</b> '+esc(a.pros.join(" · "))+'</p><small>'+esc(a.watch.join(" · "))+'</small></article>').join("");
 $("#mealPlans").innerHTML=state.stay.meal_plans.map(x=>'<div><strong>'+esc(x.code)+'</strong><span>'+esc(x.meaning)+'</span></div>').join("");
 $("#dayGrid").innerHTML=state.itineraries.duration_guides.map(x=>'<button type="button" data-days="'+x.days+'"><span>'+esc(x.label)+'</span><strong>'+esc(x.principle)+'</strong><small>'+esc(x.weather_rule||x.avoid||"")+'</small></button>').join("");
 $("#routeIdeas").innerHTML='<div class="route-answer"><span>CHỌN SỐ NGÀY Ở TRÊN</span><strong>Cẩm nang sẽ đưa đúng nhịp đi.</strong></div>';
 $$("[data-days]").forEach(b=>b.onclick=()=>{const days=Number(b.dataset.days),d=state.itineraries.duration_guides.find(x=>x.days===days),templates=state.itineraries.templates.filter(x=>x.title.startsWith(String(days)));$$("[data-days]").forEach(x=>x.classList.toggle("active",x===b));$("#routeIdeas").innerHTML='<div class="route-answer"><span>'+esc(d.label)+'</span><strong>'+esc(d.principle)+'</strong><p>'+esc(d.weather_rule||d.avoid||"")+'</p>'+(templates.length?'<div class="route-template">'+templates.map(t=>'<b>'+esc(t.title)+'</b><ol>'+t.days.map(day=>'<li>'+esc(Array.isArray(day)?day.join(" · "):day)+'</li>').join("")+'</ol>').join("")+'</div>':'')+'</div>'});
}
Promise.all([
 fetch("data.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json()),
 fetch("../data/views/search-index.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json()),
 fetch("../data/stay.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json()),
 fetch("../data/itineraries.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json()),
 fetch("../data/practical-guide.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json())
]).then(([guide,search,stay,itineraries,practical])=>{Object.assign(state,{guide,search,stay,itineraries,practical});$("#sourceMeta").textContent="Điểm đến, lịch trình và thông tin thực dụng — được sắp theo câu hỏi của bạn.";$("#handbookCoverage").textContent=(search.documents||[]).length+" mục có thể tìm";const featured=["visa","tàu cao tốc","khách sạn","Hòn Thơm","ẩm thực","APEC","Bãi Sao","meal plan"];$("#knowledgeGrid").innerHTML=featured.map((q,i)=>'<button type="button" data-guide-query="'+esc(q)+'"><span>GỢI Ý '+String(i+1).padStart(2,"0")+'</span><strong>'+esc(q)+'</strong><small>Mở thông tin liên quan</small></button>').join("");$$("[data-guide-query]").forEach(b=>b.onclick=()=>{$("#guideQ").value=b.dataset.guideQuery;renderSearch(b.dataset.guideQuery)});renderStatic();renderIntent("first");if(initialGuideQuery){$("#guideQ").value=initialGuideQuery;renderSearch(initialGuideQuery)}}).catch(e=>{$("#sourceMeta").textContent="Chưa tải được cẩm nang lúc này.";console.warn(e)});
$$("[data-intent]").forEach(b=>b.onclick=()=>renderIntent(b.dataset.intent));$("#guideSearch").onsubmit=e=>{e.preventDefault();const q=$("#guideQ").value.trim();if(q)renderSearch(q)};$("#guideQ").oninput=()=>{if(!$("#guideQ").value.trim())$("#guideSearchResults").hidden=true};
