(()=>{
const TZ='Asia/Ho_Chi_Minh';
const baseFetchSnapshot=fetchSnapshotPayload,baseRenderSummary=renderSummary;
state.boardOffset=0;
function dayVN(){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function add(day,n){const d=new Date(day+'T12:00:00+07:00');d.setUTCDate(d.getUTCDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function selected(){return add(dayVN(),state.boardOffset||0)}
function label(o){return o<0?'Hôm qua':o>0?'Ngày mai':'Hôm nay'}
function announce(){window.JOTRIP_BOARD_DATE=selected();window.dispatchEvent(new CustomEvent('jotrip:board-date',{detail:{date:window.JOTRIP_BOARD_DATE,offset:state.boardOffset}}))}
fetchLivePayload=async function(){if(!LIVE_API_URL)throw new Error('Live API chưa cấu hình');const u=new URL(LIVE_API_URL);u.searchParams.set('date',selected());u.searchParams.set('t',Date.now());const res=await fetch(u,{cache:'no-store',headers:{accept:'application/json'}});if(!res.ok)throw new Error(`JoTrip Live API HTTP ${res.status}`);const p=await res.json();if(!p?.latest?.records||!p?.health)throw new Error('JoTrip Live API trả dữ liệu không hợp lệ');return p};
fetchSnapshotPayload=async function(){if((state.boardOffset||0)!==0)throw new Error('Không dùng bản lưu hôm nay cho ngày khác');return baseFetchSnapshot()};
function apply(){const o=state.boardOffset||0,other=o!==0;document.body.classList.toggle('board-not-today',other);const h=document.querySelector('.hero h2');if(h)h.textContent=`${label(o)} tại Phú Quốc`;const bh=document.querySelector('.card.live-only .card-head h3');if(bh)bh.textContent=`Chuyến bay ${label(o).toLowerCase()}`;const pill=document.querySelector('.live-pill');if(pill)pill.innerHTML=other?'BẢNG':'<i></i> LIVE';if(other){const ops=document.querySelector('#opsState');if(ops){ops.className='ops-state';ops.textContent=o<0?'BẢNG HÔM QUA':'BẢNG NGÀY MAI'}}announce()}
function build(){const strip=document.querySelector('.source-strip');if(!strip||document.querySelector('.board-day-switch'))return;const nav=document.createElement('div');nav.className='board-day-switch';[[-1,'HÔM QUA'],[0,'HÔM NAY'],[1,'NGÀY MAI']].forEach(([o,t])=>{const b=document.createElement('button');b.type='button';b.dataset.offset=o;b.textContent=t;if(o===0)b.classList.add('active');b.onclick=()=>{state.boardOffset=Number(o);state.limit=8;state.filter='all';document.querySelectorAll('#filterChips button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',Number(x.dataset.offset)===state.boardOffset));apply();load()};nav.appendChild(b)});strip.after(nav);const cards=document.querySelectorAll('.card.live-only');if(cards[1])cards[1].classList.add('next-relative');document.querySelectorAll('.side-card.live-only').forEach(x=>x.classList.add('next-relative'))}
renderSummary=function(){baseRenderSummary();apply();if((state.boardOffset||0)!==0){const u=document.querySelector('#updatedAt');if(u)u.textContent=`Bảng ${state.latest?.source_date||selected()} · lấy lúc ${new Date(state.latest?.collected_at_vn).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:TZ})}`}};
renderNextArrivals=function(){if((state.boardOffset||0)!==0)return;const a=(state.latest?.records||[]).filter(r=>r.direction==='arrival'&&!isPastRecord(r)).sort((x,y)=>(mins(scheduledTime(x))??9999)-(mins(scheduledTime(y))??9999)).slice(0,5);$('#nextArrivalsList').innerHTML=a.length?a.map(r=>{const info=timingInfo(r),status=displayStatusLabel(r),air=airlineFor(r);return `<div class="arrival-item"><div class="arrival-time">${escapeHtml(info.scheduled||'--:--')}</div><div class="arrival-main"><strong>${escapeHtml(r.operating_flight_number)} · ${escapeHtml(stationLabel(r.station))}</strong><span class="arrival-airline">${escapeHtml(air)}</span>${isDelayed(r)&&info.expected?`<span class="arrival-estimate">Dự kiến ${escapeHtml(info.expected)}</span>`:''}</div><span class="status-pill ${statusClass(status)}">${escapeHtml(status)}</span></div>`}).join(''):'<div class="empty-state">Chưa có chuyến đến tiếp theo trong dữ liệu.</div>'};
build();apply();
})();
